# Generated by Django 4.2.5 on 2023-09-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blog_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, verbose_name="Описания"),
        ),
    ]
